[package]
name = "juneau"
version = "0.1.0"
edition = "2018"

[dependencies]
antlr-rust = "=0.2.0-dev.2"
llvm-sys = "100"
enum_dispatch = "0.3.5"
libc = "0.2"
num_cpus = "1.13.0"
notify = "4.0.15"
regex = "1.4.3"
time = "*"
num-format = "0.4.0"
tsc-time = "0.1.0"
postgres-native-tls = "0.5.0"
bytes = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
anyhow = "1.0.40"
walrus = "0.18.0"
wasmer = "1.0.2"
wasmer-compiler-cranelift = "1.0.2"
wasmer-engine-jit = "1.0.2"


juneau_core = {path = "../core/core"}